@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Initial state

package states {
    class State1 as "<u>bufferState:CommandState</u>"
    class State2 as "<u>state1:CommandState</u>"
    class State3 as "<u>state2:CommandState</u>"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3
hide State2
hide State3

class Pointer as "currentStateIdx = 0" #FFFFFF
Pointer -up-> State1
@end
